# fly.toml app configuration file generated for openwa-app on 2026-08-20T19:35:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openwa-app'
primary_region = 'jnb'

[build]

[processes]
  app = 'node ./dbsetup.js node dist/main'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 2785
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  size = 'shared-cpu-1x'

[deploy]
  release_command = 'flyctl machine update 8576e6da1e4018 \   --app openwa-app \   --image registry.fly.io/openwa-app:deployment-3dbc5ab4e909238ee9bd535e2b7776be'
  strategy = 'rolling'
