# fly.toml app configuration file generated for openwa-app on 2026-08-21T02:50:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openwa-app'
primary_region = 'ams'

[build]

[processes]
  app = 'node ./dbsetup.js node dist/main'

[[mounts]]
  source = 'openwa_data'
  destination = '/app/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 2785
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[vm]]
  memory = '512mb'
  size = 'shared-cpu-1x'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
  processes = ['app']

[deploy]
  release_command = 'flyctl machine update 8576e6da1e4018 \   --app openwa-app \   --image registry.fly.io/openwa-app:deployment-3dbc5ab4e909238ee9bd535e2b7776be'
  strategy = 'rolling'
